db.url=jdbc:mysql://localhost:23318/palma_do_campo?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
db.user=root
db.password=Girafa-trovao-meia!
db.driver=com.mysql.cj.jdbc.Driver


